name: pipelines-deployment
# on:
#   pull_request:
#     branches:    
#       - main
on: [push]
jobs:
  test-job:
    runs-on: ubuntu-20:04
    container:
      image: python:3.7
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls