# name: unit-test
# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches-ignore:
#       - main
# jobs:
#   ml-components-unit-test:
#     runs-on: ubuntu-20.04
#     container:
#       image: python:3.7
#     steps:
#       - uses: actions/checkout@v3
#       - run: apt-get update
#       - run: apt-get -y install python3-pip
#       - run: apt-get -y install uuid-runtime
#       - run: pip3 install docker-compose
#       - run: export PATH=$HOME/.local/bin:$PATH
#       - run: cd ml_components
#       - run: tests/run