name: unit-test
on:
  pull_request:
    branches:    
      - main
  push:
    branches:    
      - !main
jobs:
  test-job:
    runs-on: ubuntu-20.04
    container:
      image: python:3.7
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls